---
title: "Reading In"
author: "Elias DeLeon"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, options(scipen=999))

library(lubridate) # "Working with dates" package
library(infer) # "Statistical analysis" package
library(skimr) # "Fancy summary" package
library(broom) # "Tidy lm" package
library(gganimate) # "Animated graphs" package
library(rsconnect) # "Shiny app upload" package
library(tidymodels) # "Uniform regression / fit functions" package
library(rpart.plot) # "Grpahing CART trees" package
library(tidyverse) # "The" package
```

Link to GitHub Repository: https://github.com/Juggereggnog/final_project_v1

```{r functions, include=FALSE}
deckify <- function(data) {
  sample_deck <- read_delim(data, delim = "\n", col_names = FALSE) %>% 
    mutate(duplicates = str_extract(X1, "\\d{0,3}"),
           from_set = substr(str_extract(X1, "\\(.*?\\)"), 2, 4),
           gatherer_id = substr(str_extract(X1, "\\) \\d{0,6}"),
                                 2, nchar(X1)),
           card_name = substr(X1,
                              nchar(duplicates) + 2, nchar(X1) 
                                                   - nchar(from_set) 
                                                   - nchar(gatherer_id) - 3),
           X1 = NULL)
}

find_folder <- function(x) {
  list.files(path = paste0("magic_world_championships/magic_worlds_", x),
                    pattern = "*.txt",
                    full.names = TRUE)
}

recool <- function(x) {
  x %>%   
    rev() %>% 
    paste(collapse = " ")
}
```

```{r files, include=FALSE}
files_2015 <- find_folder(2015)

files_2016 <- find_folder(2016)

files_2017 <- find_folder(2017)

files_2018 <- find_folder(2018)

files_2020 <- find_folder(2020)

files <- c(files_2015, files_2016, files_2017, files_2018, files_2020)
```

```{r decks, include=FALSE}
decks_2015 <- tibble(File = files_2015) %>%
    extract(File, "player", "-(.*)'", remove = FALSE) %>%
    mutate(Data = map(File, deckify)) %>%
    unnest(Data) %>%
    mutate(year = 2015) %>% 
    select(-File)

decks_2016 <- tibble(File = files_2016) %>%
    extract(File, "player", "-(.*)_", remove = FALSE) %>%
    mutate(Data = map(File, deckify)) %>%
    unnest(Data) %>%
    mutate(year = 2016) %>% 
    select(-File)

decks_2017 <- tibble(File = files_2017) %>%
    extract(File, "player", "([A-Z][a-z]+, [A-Z][a-z]+)", remove = FALSE) %>%
    mutate(Data = map(File, deckify)) %>%
    unnest(Data) %>%
    mutate(year = 2017, player = map(strsplit(player, ", "), recool)) %>% 
    select(-File)

decks_2018 <- tibble(File = files_2018) %>%
    extract(File, "player", "([A-Z][a-z]+, [A-Z][a-z]+)", remove = FALSE) %>%
    mutate(Data = map(File, deckify)) %>%
    unnest(Data) %>%
    mutate(year = 2018, player = map(strsplit(player, ", "), recool)) %>% 
    select(-File)

decks_2020 <- tibble(File = files_2020) %>%
    extract(File, "player", "([A-Z][a-z]+-[A-Z][a-z]+)", remove = FALSE) %>%
    mutate(Data = map(File, deckify)) %>%
    unnest(Data) %>%
    mutate(year = 2020,
           player = map(strsplit(player, "-"), paste, collapse = " ")) %>% 
    select(-File)

decks <- rbind(decks_2015, decks_2016, decks_2017, decks_2018, decks_2020) %>% 
  unnest(player) %>% 
  mutate(player = recode(player, "Damo da Rosa" = "Paulo Vitor Damo da Rosa",
                                 "Paulo Rosa" = "Paulo Vitor Damo da Rosa",
                                 "Paulo Vitor" = "Paulo Vitor Damo da Rosa",
                                 "Brian Duin" = "Brian Braun-Duin",
                                 "Josh Leyton" = "Josh Utter-Leyton",
                                 "Jean Emmanuel" = "Jean-Emmanuel Depraz",
                                 "Brad Nelson" = "Bradley Nelson"),
         ranking = case_when(
           (year == 2015 & player == "Seth Manfield") ~ 1,
           (year == 2015 & player == "Owen Turtenwald") ~ 2,
           (year == 2015 & player == "Paul Rietzl") ~ 3,
           (year == 2015 & player == "Samuel Black") ~ 4,
           (year == 2015 & player == "Magnus Lantto") ~ 5,
           (year == 2015 & player == "Martin Muller") ~ 6,
           (year == 2015 & player == "Shaun McLaren") ~ 7,
           (year == 2015 & player == "Thiago Saporito") ~ 8,
           (year == 2015 & player == "Ondrej Strasky") ~ 9,
           (year == 2015 & player == "Yuuya Watanabe") ~ 10,
           (year == 2015 & player == "Paulo Vitor Damo da Rosa") ~ 11,
           (year == 2015 & player == "Jacob Wilson") ~ 12,
           (year == 2015 & player == "Joel Larsson") ~ 13,
           (year == 2015 & player == "Alexander Hayne") ~ 14,
           (year == 2015 & player == "Martin Dang") ~ 15,
           (year == 2015 & player == "Steve Rubin") ~ 16,
             (year == 2016 & player == "Brian Braun-Duin") ~ 1,
             (year == 2016 & player == "Marcio Carvalho") ~ 2,
             (year == 2016 & player == "Oliver Tiu") ~ 3,
             (year == 2016 & player == "Shota Yasooka") ~ 4,
             (year == 2016 & player == "Lukas Blohon") ~ 5,
             (year == 2016 & player == "Luis Scott-Vargas") ~ 6,
             (year == 2016 & player == "Jiachen Tao") ~ 7,
             (year == 2016 & player == "Seth Manfield") ~ 8,
             (year == 2016 & player == "Thiago Saporito") ~ 9,
             (year == 2016 & player == "Steve Rubin") ~ 10,
             (year == 2016 & player == "Mike Sigrist") ~ 11,
             (year == 2016 & player == "Reid Duke") ~ 12,
             (year == 2016 & player == "Bradley Nelson") ~ 13,
             (year == 2016 & player == "Joel Larsson") ~ 14,
             (year == 2016 & player == "Paulo Vitor Damo da Rosa") ~ 15,
             (year == 2016 & player == "Yuuya Watanabe") ~ 16,
               (year == 2017 & player == "William Jensen") ~ 1,
               (year == 2017 & player == "Javier Dominguez") ~ 2,
               (year == 2017 & player == "Josh Utter-Leyton") ~ 3,
               (year == 2017 & player == "Kelvin Chew") ~ 4,
               (year == 2017 & player == "Reid Duke") ~ 5,
               (year == 2017 & player == "Samuel Black") ~ 6,
               (year == 2017 & player == "Seth Manfield") ~ 7,
               (year == 2017 & player == "Owen Turtenwald") ~ 8,
               (year == 2017 & player == "Gerry Thompson") ~ 9,
               (year == 2017 & player == "Shota Yasooka") ~ 10,
               (year == 2017 & player == "Christian Calcano") ~ 11,
               (year == 2017 & player == "Paulo Vitor Damo da Rosa") ~ 12,
               (year == 2017 & player == "Eric Froehlich") ~ 13,
               (year == 2017 & player == "Sebastian Pozzo") ~ 14,
               (year == 2017 & player == "Bradley Nelson") ~ 15,
               (year == 2017 & player == "Martin Juza") ~ 16,
                 (year == 2018 & player == "Javier Dominguez") ~ 1,
                 (year == 2018 & player == "Grzegorz Kowalski") ~ 2,
                 (year == 2018 & player == "Benjamin Stark") ~ 3,
                 (year == 2018 & player == "Shahar Shenhar") ~ 4,
                 (year == 2018 & player == "Allen Wu") ~ 5,
                 (year == 2018 & player == "Wyatt Darby") ~ 6,
                 (year == 2018 & player == "Matthew Nass") ~ 7,
                 (year == 2018 & player == "Ben Hull") ~ 8,
                 (year == 2018 & player == "Reid Duke") ~ 9,
                 (year == 2018 & player == "Mike Sigrist") ~ 10,
                 (year == 2018 & player == "John Rolf") ~ 11,
                 (year == 2018 & player == "Marcio Carvalho") ~ 12,
                 (year == 2018 & player == "Bradley Nelson") ~ 13,
                 (year == 2018 & player == "Elias Watsfeldt") ~ 14,
                 (year == 2018 & player == "Brian Braun-Duin") ~ 15,
                 (year == 2018 & player == "Luis Salvatto") ~ 16,
                   (year == 2020 & player == "Paulo Vitor Damo da Rosa") ~ 1,
                   (year == 2020 & player == "Marcio Carvalho") ~ 2,
                   (year == 2020 & player == "Seth Manfield") ~ 3,
                   (year == 2020 & player == "Gabriel Nassif") ~ 4,
                   (year == 2020 & player == "Sebastian Pozzo") ~ 5,
                   (year == 2020 & player == "Eli Loveman") ~ 6,
                   (year == 2020 & player == "Jean-Emmanuel Depraz") ~ 7,
                   (year == 2020 & player == "Autumn Burchett") ~ 8,
                   (year == 2020 & player == "Piotr Glogowski") ~ 9,
                   (year == 2020 & player == "Chris Kvartek") ~ 10,
                   (year == 2020 & player == "Raphael Levy") ~ 11,
                   (year == 2020 & player == "Thoralf Severin") ~ 12,
                   (year == 2020 & player == "Ondrej Strasky") ~ 13,
                   (year == 2020 & player == "Javier Dominguez") ~ 14,
                   (year == 2020 & player == "Andrea Mengucci") ~ 15,
                   (year == 2020 & player == "Matias Leveratto") ~ 16,
           TRUE ~ 9999999),
         winnings_dollars = case_when(
           (year == 2015 & player == "Seth Manfield") ~ 50000,
           (year == 2015 & player == "Owen Turtenwald") ~ 20000,
           (year == 2015 & player == "Paul Rietzl") ~ 10000,
           (year == 2015 & player == "Samuel Black") ~ 10000,
           (year == 2015 & player == "Magnus Lantto") ~ 5000,
           (year == 2015 & player == "Martin Muller") ~ 5000,
           (year == 2015 & player == "Shaun McLaren") ~ 5000,
           (year == 2015 & player == "Thiago Saporito") ~ 5000,
           (year == 2015 & player == "Ondrej Strasky") ~ 3000,
           (year == 2015 & player == "Yuuya Watanabe") ~ 3000,
           (year == 2015 & player == "Paulo Vitor Damo da Rosa") ~ 3000,
           (year == 2015 & player == "Jacob Wilson") ~ 3000,
           (year == 2015 & player == "Joel Larsson") ~ 3000,
           (year == 2015 & player == "Alexander Hayne") ~ 3000,
           (year == 2015 & player == "Martin Dang") ~ 3000,
           (year == 2015 & player == "Steve Rubin") ~ 3000,
             (year == 2016 & player == "Brian Braun-Duin") ~ 70000,
             (year == 2016 & player == "Marcio Carvalho") ~ 40000,
             (year == 2016 & player == "Oliver Tiu") ~ 20000,
             (year == 2016 & player == "Shota Yasooka") ~ 20000,
             (year == 2016 & player == "Lukas Blohon") ~ 10000,
             (year == 2016 & player == "Luis Scott-Vargas") ~ 10000,
             (year == 2016 & player == "Jiachen Tao") ~ 10000,
             (year == 2016 & player == "Seth Manfield") ~ 10000,
             (year == 2016 & player == "Thiago Saporito") ~ 5000,
             (year == 2016 & player == "Steve Rubin") ~ 5000,
             (year == 2016 & player == "Mike Sigrist") ~ 5000,
             (year == 2016 & player == "Reid Duke") ~ 5000,
             (year == 2016 & player == "Bradley Nelson") ~ 5000,
             (year == 2016 & player == "Joel Larsson") ~ 5000,
             (year == 2016 & player == "Paulo Vitor Damo da Rosa") ~ 5000,
             (year == 2016 & player == "Yuuya Watanabe") ~ 5000,
               (year == 2017 & player == "William Jensen") ~ 100000,
               (year == 2017 & player == "Javier Dominguez") ~ 50000,
               (year == 2017 & player == "Josh Utter-Leyton") ~ 25000,
               (year == 2017 & player == "Kelvin Chew") ~ 25000,
               (year == 2017 & player == "Reid Duke") ~ 10000,
               (year == 2017 & player == "Samuel Black") ~ 10000,
               (year == 2017 & player == "Seth Manfield") ~ 10000,
               (year == 2017 & player == "Owen Turtenwald") ~ 10000,
               (year == 2017 & player == "Gerry Thompson") ~ 5000,
               (year == 2017 & player == "Shota Yasooka") ~ 5000,
               (year == 2017 & player == "Christian Calcano") ~ 5000,
               (year == 2017 & player == "Paulo Vitor Damo da Rosa") ~ 5000,
               (year == 2017 & player == "Eric Froehlich") ~ 5000,
               (year == 2017 & player == "Sebastian Pozzo") ~ 5000,
               (year == 2017 & player == "Bradley Nelson") ~ 5000,
               (year == 2017 & player == "Martin Juza") ~ 5000,
                 (year == 2018 & player == "Javier Dominguez") ~ 100000,
                 (year == 2018 & player == "Grzegorz Kowalski") ~ 50000,
                 (year == 2018 & player == "Benjamin Stark") ~ 25000,
                 (year == 2018 & player == "Shahar Shenhar") ~ 25000,
                 (year == 2018 & player == "Allen Wu") ~ 10000,
                 (year == 2018 & player == "Wyatt Darby") ~ 10000,
                 (year == 2018 & player == "Matthew Nass") ~ 10000,
                 (year == 2018 & player == "Ben Hull") ~ 10000,
                 (year == 2018 & player == "Reid Duke") ~ 5000,
                 (year == 2018 & player == "Mike Sigrist") ~ 5000,
                 (year == 2018 & player == "John Rolf") ~ 5000,
                 (year == 2018 & player == "Marcio Carvalho") ~ 5000,
                 (year == 2018 & player == "Bradley Nelson") ~ 5000,
                 (year == 2018 & player == "Elias Watsfeldt") ~ 5000,
                 (year == 2018 & player == "Brian Braun-Duin") ~ 5000,
                 (year == 2018 & player == "Luis Salvatto") ~ 5000,
                   (year == 2020 & player == "Paulo Vitor Damo da Rosa") 
                                                                ~ 300000,
                   (year == 2020 & player == "Marcio Carvalho") ~ 150000,
                   (year == 2020 & player == "Seth Manfield") ~ 100000,
                   (year == 2020 & player == "Gabriel Nassif") ~ 75000,
                   (year == 2020 & player == "Sebastian Pozzo") ~ 62500,
                   (year == 2020 & player == "Eli Loveman") ~ 62500,
                   (year == 2020 & player == "Jean-Emmanuel Depraz") ~ 50000,
                   (year == 2020 & player == "Autumn Burchett") ~ 50000,
                   (year == 2020 & player == "Piotr Glogowski") ~ 25000,
                   (year == 2020 & player == "Chris Kvartek") ~ 25000,
                   (year == 2020 & player == "Raphael Levy") ~ 25000,
                   (year == 2020 & player == "Thoralf Severin") ~ 25000,
                   (year == 2020 & player == "Ondrej Strasky") ~ 12500,
                   (year == 2020 & player == "Javier Dominguez") ~ 12500,
                   (year == 2020 & player == "Andrea Mengucci") ~ 12500,
                   (year == 2020 & player == "Matias Leveratto") ~ 12500,
           TRUE ~ 9999999),
         card_name = map(card_name,
                         ~ ifelse(str_detect(., " $") == TRUE,
                                  substr(.,
                                         start = 1,
                                         stop = nchar(.) - 1), .)),
         card_name = map(card_name,
                         ~ ifelse(str_detect(., "//") == TRUE,
                                  str_split(., " // "), .)),
         card_name = map(card_name, ~ unlist(.)[1])) %>% 
  unnest(card_name) %>% 
  select(-gatherer_id, -from_set)

decks$duplicates <- as.numeric(decks$duplicates)

split_cards <- decks %>% 
  filter(str_detect(decks$card_name, "//") == TRUE) %>% 
  distinct(card_name) %>%  
  separate(card_name, into = c("first", "second"), sep = " // ")
```

```{r mtgjson}
cards <- read_csv("AllPrintingsCSVFiles/cards.csv",
                  guess_max = 200000,
                  col_types = cols(
                    index = col_double(),
                    id = col_double(),
                    artist = col_character(),
                    borderColor = col_character(),
                    colorIdentity = col_character(),
                    colorIndicator = col_character(),
                    colors = col_character(),
                    convertedManaCost = col_double(),
                    duelDeck = col_character(),
                    edhrecRank = col_double(),
                    faceConvertedManaCost = col_double(),
                    flavorText = col_character(),
                    frameEffect = col_character(),
                    frameEffects = col_character(),
                    frameVersion = col_character(),
                    hand = col_double(),
                    hasFoil = col_double(),
                    hasNoDeckLimit = col_double(),
                    hasNonFoil = col_double(),
                    isAlternative = col_double(),
                    isArena = col_double(),
                    isBuyABox = col_double(),
                    isDateStamped = col_double(),
                    isFullArt = col_double(),
                    isMtgo = col_double(),
                    isOnlineOnly = col_double(),
                    isOversized = col_double(),
                    isPaper = col_double(),
                    isPromo = col_double(),
                    isReprint = col_double(),
                    isReserved = col_double(),
                    isStarter = col_double(),
                    isStorySpotlight = col_double(),
                    isTextless = col_double(),
                    isTimeshifted = col_double(),
                    layout = col_character(),
                    leadershipSkills = col_character(),
                    life = col_double(),
                    loyalty = col_character(),
                    manaCost = col_character(),
                    mcmId = col_double(),
                    mcmMetaId = col_double(),
                    mtgArenaId = col_double(),
                    mtgoFoilId = col_double(),
                    mtgoId = col_double(),
                    multiverseId = col_double(),
                    name = col_character(),
                    names = col_character(),
                    number = col_character(),
                    originalText = col_character(),
                    originalType = col_character(),
                    otherFaceIds = col_character(),
                    power = col_character(),
                    printings = col_character(),
                    purchaseUrls = col_character(),
                    rarity = col_character(),
                    scryfallId = col_character(),
                    scryfallIllustrationId = col_character(),
                    scryfallOracleId = col_character(),
                    setCode = col_character(),
                    side = col_character(),
                    subtypes = col_character(),
                    supertypes = col_character(),
                    tcgplayerProductId = col_double(),
                    text = col_character(),
                    toughness = col_character(),
                    type = col_character(),
                    types = col_character(),
                    uuid = col_character(),
                    variations = col_character(),
                    watermark = col_character()
                  ))

prices <- read_csv("AllPrintingsCSVFiles/prices.csv",
                   col_types = cols(
                     index = col_double(),
                     id = col_double(),
                     date = col_date(format = ""),
                     price = col_double(),
                     type = col_character(),
                     uuid = col_character()
                   )) %>% 
  filter(type == "paper") %>% 
  select(price, uuid)

sets <- read_csv("AllPrintingsCSVFiles/sets.csv",
                 col_types = cols(
                   index = col_double(),
                   id = col_double(),
                   baseSetSize = col_double(),
                   block = col_character(),
                   boosterV3 = col_character(),
                   code = col_character(),
                   codeV3 = col_character(),
                   isFoilOnly = col_double(),
                   isForeignOnly = col_double(),
                   isOnlineOnly = col_double(),
                   isPartialPreview = col_double(),
                   keyruneCode = col_character(),
                   mcmId = col_double(),
                   mcmName = col_character(),
                   meta = col_character(),
                   mtgoCode = col_character(),
                   name = col_character(),
                   parentCode = col_character(),
                   releaseDate = col_date(format = ""),
                   tcgplayerGroupId = col_double(),
                   totalSetSize = col_double(),
                   type = col_character()
                 )) %>% 
  select(-index, -id)
```

```{r joining_tables, warning=FALSE}
full_table <- cards %>% 
  left_join(sets, by = c("setCode" = "code"), suffix = c("_card", "_set")) %>% 
  left_join(prices, by = "uuid") %>% 
  filter(baseSetSize != 0,
         ! type_set %in% c("masters", "promo", "funny"),
         ! is.na(as.numeric(number))) %>% 
  distinct(name_card, .keep_all = TRUE) %>% 
  mutate(power = ifelse(power > 0, as.numeric(power), 0),
         power = ifelse(is.na(power) & types == "Creature", 0, power),
         toughness = ifelse(toughness > 0, as.numeric(toughness), 0),
         toughness = ifelse(is.na(toughness) & types == "Creature", 0, power),
         loyalty = as.numeric(loyalty),
         in_tournament = ifelse(name_card %in% decks$card_name |
                                paste0(name_card, " ") %in% decks$card_name |
                                name_card %in% split_cards$first, 1, 0)) %>% 
  select(index, id, price, name_card, names, power, toughness, loyalty,
         convertedManaCost, manaCost, colors, colorIdentity, supertypes, types,
         subtypes, rarity, text, layout, name_set, mcmName, setCode,
         releaseDate, type_set, baseSetSize, totalSetSize, block, parentCode,
         printings, number, borderColor, edhrecRank, multiverseId,
         in_tournament)
```

```{r decks_addendum}
tournament_cards <- full_table %>% 
  filter(in_tournament == 1)

decks_full_table <- decks %>% 
  inner_join(tournament_cards, by = c("card_name" = "name_card")) %>% 
  select(-in_tournament, -index, -id)
```

```{r graph_earnings}
ggdecks <- decks %>% 
  group_by(player, winnings_dollars) %>% 
  summarize() %>% 
  ungroup() %>% 
  group_by(player) %>% 
  summarize(total_winnings = sum(winnings_dollars)) %>% 
  arrange(desc(total_winnings)) %>% 
  head(10)

earnings <- ggplot(ggdecks,
                   aes(fct_reorder(player, total_winnings), total_winnings)) +
  geom_col() +
  coord_flip() +
  labs(title = "Total Earnings of Magic World Championship Players 2015-2020",
       subtitle = "Damo da Rosa is considered one of the best players of all time;
highest earners are skewed towards recent years due to higher prize pools",
       caption = "Source: Wizards of the Coast Event Coverage") +
  xlab("Player") +
  ylab("Total Winnings ($)") +
  theme_bw() +
  theme(axis.text.y = element_text(angle = 40))

ggsave("earnings.png",
       plot = earnings,
       path = "shiny_magic")
```

```{r graphs_test}
full_table %>% 
  select(power, price, toughness) %>% 
  filter(! is.na(power), ! is.na(price), ! is.na(toughness)) %>% 
  cor()


ggplot(full_table, aes(rarity)) +
  geom_bar()


ggplot(full_table, aes(toughness, price, color = rarity)) +
  geom_point() +
  geom_jitter(alpha = 0.4) +
  labs(y = "Price") +
  scale_y_continuous(limits = c(0, 1000))


rare_model <- lm(price ~ rarity, data = full_table)

rare_model %>% 
  tidy(conf.int = TRUE) %>% 
  select(term, estimate, conf.low, conf.high)


tournament_model <- lm(price ~ in_tournament, data = full_table)

tournament_model %>% 
  tidy(conf.int = TRUE) %>% 
  select(term, estimate, conf.low, conf.high)


stats_model <- lm(price ~ power + toughness + rarity + in_tournament +
                          types + colors + convertedManaCost + name_set +
                          edhrecRank,
                  data = full_table)

stats_model %>% 
  tidy(conf.int = TRUE) %>% 
  select(term, estimate, conf.low, conf.high)


# tree_mod <- decision_tree() %>%
#   set_engine("rpart",
#              model = TRUE) %>%
#   set_mode("classification")
# 
# tournament_tree <- fit(tree_mod,
#                   factor(in_tournament) ~ power + toughness,
#                   data = full_table)
# 
# tournament_tree$fit %>% 
#   prp(extra = 4, varlen = 0, faclen = 0)

# CART classification, tree for determining if card was in tournament
# usually a predictive model (with categorical outcomes)

# regression is more of an explanatory model
```

```{r saving}
write_rds(full_table, "shiny_magic/full_table.rds")

write_rds(decks_full_table, "shiny_magic/decks_full_table.rds")

write_rds(tournament_cards, "shiny_magic/tournament_cards.rds")
```

